### ISSUE TITLE
[Feature Request] add link to jellyfin item on webhook Item Added

### ISSUE THREAD

**Issue by mLgz0rn** [Notifiarr/website#107]
Hey!

As the title suggest it would be awesome if it would also be possible to add a link to the movie/show recently added on the Item Added webhook for jellyfin like there are also links to tmdb and so.
I have no idea is this has been suggested, I couldn't find it though.

Kind regards!

**Comment by austinwbest** [comment]
Quick glance at the code, it should already have links in the messages if it finds the meta data for it. Do you have the links setting enabled in the notification options?

![image](https://user-images.githubusercontent.com/8321115/153756099-e7e7e577-8450-4e41-b56f-d34bbd66c0b0.png)

![image](https://user-images.githubusercontent.com/8321115/153756043-cae1a089-eb5e-4d6b-a6b8-94bdf8b9c777.png)

**Comment by mLgz0rn** [comment]
I think you misunderstood :D Or I was bad at describing.
What I mean is there also being a link to the movie or show on jellyfin itself when added.

So if I use your image.
![153756099-e7e7e577-8450-4e41-b56f-d34bbd66c0b0 kopier](https://user-images.githubusercontent.com/6141439/153765911-57ded0b8-d27a-457d-9d6f-b765ae027a95.png)

and then the Jellyfin link would link to Cherry on the jellyfin web instance

Just like you have a local link for radarr and sonarr

**Comment by austinwbest** [comment]
Ah, ok i understand now

**Comment by austinwbest** [comment]
> Just like you have a local link for radarr and sonarr

Can you provide me with a link to something? I need to see if the data in the payload provides all the pieces to rebuild a full link

You can replace your domain with a fake one but the rest wild need to be right

**Comment by mLgz0rn** [comment]
> > Just like you have a local link for radarr and sonarr
> 
> Can you provide me with a link to something? I need to see if the data in the payload provides all the pieces to rebuild a full link
> 
> You can replace your domain with a fake one but the rest wild need to be right

Yes of course
http://domain/web/index.html#!/details?
id=8b1efd9614abf8b5b7c95f8765f78331&serverId=649e7a5d94b54549bf98f28d962e51d6
This would be the default one.

I however have changed location block for /web so it dosnt show the index.html to reduce the link size a bit and for aesthetics.
(It's also suggested on Jellyfin's documentation when using a reverse proxy)
https://domain/web/#!/details?id=8b1efd9614abf8b5b7c95f8765f78331&serverId=649e7a5d94b54549bf98f28d962e51d6

Don't know if it would be possible to make both things work, or it's one or another.
Or maybe add so we ourself fill in the link and then have a {ServerUrl}, {ItemId} and {ServerId} tag

Thats how they do it for the webhooks plugin in jellyfin itself

[Jellyfin] ({{ServerUrl}}/web/#!/details?id={{ItemId}}&serverId={{ServerId}})

**Comment by austinwbest** [comment]
Yea, I would have a spot on the site for the path and then add the rest of the dynamic bits in

**Comment by mLgz0rn** [comment]
Awesome! Thank you so much

**Comment by austinwbest** [comment]
> Awesome! Thank you so much

Setting options are pushed. Let me know if you have any issues with it as i dont use JF but it should work fine

**Comment by mLgz0rn** [comment]
Hey.

It does not seem to be working, I added the url to Local URL, but it does not seem to show up on the notification in discord

**Comment by austinwbest** [comment]
> Hey.
> 
> It does not seem to be working, I added the url to Local URL, but it does not seem to show up on the notification in discord

Hop on discord if you would, alot easier to troubleshoot in real time :)
