### ISSUE TITLE
Add Discover for Books

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#117]
title

**Comment by austinwbest** [comment]
I'm not even sure where to start. The lists on GR are not practical. Thousands of lists with thousands of books in them..

Is there somewhere with a top 200 per genre kinda thing? Like I do with radarr/sonarr & imdb

**Comment by austinwbest** [comment]
Reopen this if you find a usable source for lists that can be grabbed. A genre top 100 or similar to how movies and what not is.
