### ISSUE TITLE
Missing Instance Name for On Downloads (Radarr)

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#128]
![image](https://user-images.githubusercontent.com/55419169/163651851-ff67b0bf-757b-4e3c-985a-f7a4b8501751.png)
![image](https://user-images.githubusercontent.com/55419169/163651870-0ffc8f45-fa09-46f7-855b-89b64182ac96.png)

Radarr Trace has the instance - https://notifiarr.com/notifier.php: api=(removed)&instanceName=Radarr4k

**Comment by austinwbest** [comment]
Fixed on dev
