### ISSUE TITLE
Sonarr tags not being included when adding from MDBList

### ISSUE THREAD

**Issue by ttw1203** [Notifiarr/website#145]
Sonarr tags are not being included in the shows added from MDBList even after specifying the tags field in the integration setup. Radarr tags on the other hand are working as expected. Notifiarr is connected through webhook in Sonarr.
[Debug log](https://0bin.net/paste/NgVMcx+P#WPO+mDrVyHYjc1uZjXuBPv3ALnlcr8QK307lIQ4PS9H)
Any help would be much appreciated.

**Comment by mataus19** [comment]
> Sonarr tags are not being included in the shows added from MDBList even after specifying the tags field in the integration setup. Radarr tags on the other hand are working as expected. Notifiarr is connected through webhook in Sonarr. [Debug log](https://0bin.net/paste/NgVMcx+P#WPO+mDrVyHYjc1uZjXuBPv3ALnlcr8QK307lIQ4PS9H) Any help would be much appreciated.

Hi, did you find a solution to this as I'm having exactly the same problem. I clicked the links below but can't find your log. Thanks
