### ISSUE TITLE
Support custom RSS feeds

### ISSUE THREAD

**Issue by Nojwe** [Notifiarr/website#147]
It would be great to be able to add custom RSS feeds through the RSS plugin.

**Comment by austinwbest** [comment]
UI is done, backend is a bit tricky but should have it done this evening hopefully..

![image](https://user-images.githubusercontent.com/8321115/172741072-8b82af89-ce55-448f-b7c9-e252e8a29afb.png)
![image](https://user-images.githubusercontent.com/8321115/172741082-771ae710-3610-4d2b-8631-cf671d622251.png)
![image](https://user-images.githubusercontent.com/8321115/172741089-099d46d5-1d0d-460f-9ae2-4bff88caf3a6.png)

**Comment by austinwbest** [comment]
This is available on dev and will be in the next push.

![image](https://user-images.githubusercontent.com/8321115/172761282-ff60efc1-b524-4a7e-9cf1-eb24b4710d10.png)
