### ISSUE TITLE
Client Updates (next version)

### ISSUE THREAD

**Issue by davidnewhall** [Notifiarr/website#152]
Putting notes here for the next client release: [v0.3.2](https://github.com/Notifiarr/notifiarr/releases/tag/v0.3.2), Jupiter Saloon.

## Features

Some of these still need website updates. 
|Done|Feature|Note|
|---|---|--|
|&check;|File and Log Watcher support.|**(1)**
|_|New file browser for UI. Used for log files, cert files, commands and file watcher.
|_|Plex sessions tracker. We now send "fake" web hooks based on tracking Plex sessions.|**(3)**
|_|More application metrics are collected.|
|_|Application instances can now be disabled by setting timeout to disabled.|
|&check;|Support multiple megaRaid volumes.|**(2)**
|&check;|Adds API endpoints for Plex: empty trash, getLibraries, and mark item watched.
|_|Now stores Unique Host ID in config file.
|&check;|New API endpoints for Sonarr and Radarr: delete custom formats, delete release profile, delete quality profile.|**(2)** **(4)**
|&check;|NZBGet integration for Dashboard and service checks.|**(1)**
|&check;|rTorrent integration for Dashboard and service checks.|**(1)** **(4)**
|&check;|Custom commands integration for Simon says.|**(1)** **(2)** **(4)**
|&check;|Adds new endpoint `/api/info` to get command list. Same as version minus app versions.|**(2)**
|&check;|Split CF sync (radarr) and RP sync (sonarr) to separate API methods.|**(2)**
|&check;|Adds Nvidia SMI integration to display GPU %, memory, and temperature in snapshots.|**(2)** **(4)**

## Other Fixes
- UI Updated: system page
- Several race condition fixes.
- Docker image updates.
- Bug fix for new Tautulli release.
- Fixes ability to create new media app integrations in UI (Plex/Tautulli).
- Fixes Readarr integration with missing author struct in book payload.
- Refactored website and trigger modules.
- Updates golang dependencies.
- Removes "tags" from a Readarr payload. **(2)**
- Removes startup URL test for Starr apps.
- All website requests are now sent to a dedicated thread and serialized.

## Notes
1. Requires new website integration.
2. Requires updating an existing website integration.
3. The data sent to website could be better, but requires integration updates.
4. Not fully test or merged.

**Comment by austinwbest** [comment]
Everything server side is done from the list. Button it up and send it :)
