### ISSUE TITLE
FR: Add String Check for Website Status

### ISSUE THREAD

**Issue by YozoraXCII** [Notifiarr/website#153]
Feature Request:

Allow Website Status to check for a specific string on a page before reporting the website as down.

As an example, https://status.themoviedb.org/ tracks multiple components, so it would be useful to check the Component Status table for a "Under Maintenance", "Degraded Performance" "Partial Outage" and "Major Outage"string to notify that something is down.

**Comment by austinwbest** [comment]
As this has not come up again by anyone else, im not really sure the work and resources to scrape html for regex matches is in the near future. I'll re-open it there is more people interested in it.
