### ISSUE TITLE
Move the last few integrations to the API

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/website#160]
- [x] Radarr - downstream [v4.2.0.6438](https://github.com/Radarr/Radarr/commit/61f05710f56f035d6c32127e6fa36b099d5efede)
- [x] Lidarr (legacy is backwards compatible) - downstream [v1.1.1.2732](https://github.com/Lidarr/Lidarr/commit/8bb630c5db81c91f18d31f642c7de2e0960af9ea)
- [x] Prowlarr (legacy is backwards compatible) - downstream [PR](https://github.com/Prowlarr/Prowlarr/pull/1063)
- [x] Readarr (legacy is backwards compatible) - downstream [PR](https://github.com/Readarr/Readarr/pull/1739)
- [x] Jellyfin (legacy is eol)
- [x] Emby (legacy is eol)
- [x] Overseerr (legacy is eol)

**Comment by austinwbest** [comment]
Everything is moved on dev, once the PRs land in the starr apps they will just work as normal

**Comment by bakerboy448** [comment]
Downstream PRs are all ready for  approval/merge. and are otherwise ready to go
