### ISSUE TITLE
smartctl and drive usage changes for Mac and windows

### ISSUE THREAD

**Issue by davidnewhall** [Notifiarr/website#167]
smartctl works on Mac and Windows, but we need to fix the Discord notifications a bit. This also affects the drive usage, at least on macOS.

For MacOS (Darwin), check each partition for duplication and ignore duplicates. Basically, if the partition has the same size and free space as another one, do not add its size and free space to the total, ignore it.

For Windows, we still need to dial in the smartctl usage. I went ahead and added all the disks to the output, but it may not be in a usable format for you. Please test unstable and let me know.

**Comment by austinwbest** [comment]
More disk options where added previously. Added a dedupe for volumes/mounts for mac, it is on dev.
