### ISSUE TITLE
Overseerr go to wrong channel

### ISSUE THREAD

**Issue by snupple** [Notifiarr/website#176]
The Overserr "Available" & "Approved" notifications and not going to the channel that is selected and instead go to another channel

**Comment by bakerboy448** [comment]
Moving to the site; not a client issue

**Comment by bakerboy448** [comment]
Doesn't appear to be a bug?

you have all of overseer's notifications assigned to the same channel `1006100579577245706` review your settings and we can reopen if it persists.  Swing by discord then

**Comment by snupple** [comment]
Yes I have them all going to the same channel (thats how I want it) but the "Available" & "Approved' are  being sent to a different channel (432156773991055360) for some reason?
