### ISSUE TITLE
[Feature Request] Dockerhub Webhook

### ISSUE THREAD

**Issue by DrSeussFreak** [Notifiarr/website#18]
Just like the integration into github, I would love to see this for dockerhub

**Comment by austinwbest** [comment]
Mentioned on discord but just so there is a response for others as well, add https://notifiarr.com/notifierTest.php?testing=Dockerhub as a webhook wherever you can and that will send test payloads for review.

**Comment by davidnewhall** [comment]
Done. 
![Screen Shot 2021-07-03 at 7 45 07 PM](https://user-images.githubusercontent.com/2402929/124371501-2e1e9400-dc37-11eb-8757-a135a2f4a3c3.png)

**Comment by DrSeussFreak** [comment]
I will test this out now.  So for this, no configuration on the notifiarr side, only the webhook addition in dockerhub?

**Comment by davidnewhall** [comment]
There's nothing to "test" yet. You're welcome to add the webhook like I did (screenshot). That sends the payloads to notifiarr.com so @austinwbest can see them and start building the integration. I suspect he'll work on this over the next couple weeks.

**Comment by austinwbest** [comment]
This one slipped through the cracks, sorry. Is this something you're still wanting to see @DrSeussFreak ?

**Comment by DrSeussFreak** [comment]
I think it would be a cool feature, but since dockerhub wants me to pay them for free repos I used to manage, I said F-them, so, for me, this is no longer needed, but thanks

**Comment by austinwbest** [comment]
Haha, fair enough. Then i'll close it and someone else can revive it if there is a need.
