### ISSUE TITLE
Extra "@" in Snapshot's mention

### ISSUE THREAD

**Issue by solid-pixel** [Notifiarr/website#185]

**Comment by austinwbest** [comment]
Screenshot please? I've got tons of these pings and never had an extra so I'm not sure if it is specific to an item or not

**Comment by solid-pixel** [comment]
not sure why this is empty now and why a clone has appeared here: https://github.com/Notifiarr/website/issues/186
but you can disregard this and check #186 instead :)

**Comment by austinwbest** [comment]
I did, just closed this when you added the other.

**Comment by solid-pixel** [comment]
didn't even know I had created two, weird. Sorry about that!
