### ISSUE TITLE
Extra `@` in Snapshot's mention for `@everyone`

### ISSUE THREAD

**Issue by solid-pixel** [Notifiarr/website#186]
Hello!

I just noticed that if you pick `@everyone` in a Snapshot trigger's mention, an extra`@` will be added in front, leading to the mention not notifying anyone:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/18260178/190860294-e4798f1e-cc07-4908-96a5-5c2cf37cf868.png">

will lead to:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/18260178/190860331-3b46efdc-14c9-410c-a010-bb0b1cedb324.png">

Other mentions seem to be working fine though.

Thanks

**Comment by austinwbest** [comment]
OK, so it is specific to everyone. I'll adjust it

**Comment by austinwbest** [comment]
Ok, so this is interesting.. Im not sure if it'll even work if i remove the @ symbol.

```
[role] => 894641917206364170
```

This is the role id, so in order to ping a role with a bot you use 

```
<@&role-id-here>
```

The everyone group just happens to have an @ in the name visually via discord so if i leave it out, i dont think it'll ping it

**Comment by austinwbest** [comment]
As the role name has an @ in it and the @ is required to ping with the bot, this just kinda is what it is i believe...
