### ISSUE TITLE
Series poster size not restricted on the new current follows page

### ISSUE THREAD

**Issue by jvgoch** [Notifiarr/website#199]
Some series on TVDB have huge posters if these are added to the current follows page. This makes the ui almost unusable. (see attached image). Not all series on the TVDB have big posterd but for example https://thetvdb.com/series/lego-city does. The issue doesn't seem to affect movies because it only parses thumbnails from TMDB, while it seems to parse big images from TVDB for series.
![image](https://user-images.githubusercontent.com/78982569/193408801-76c370d3-5f74-4c95-8a29-d1ec847846f7.png)

**Comment by austinwbest** [comment]
I didn't see this behaviour and still dont, but i will set explicit sizes anyways.

![image](https://user-images.githubusercontent.com/8321115/193410730-b11c04cb-5ee2-4e05-b35d-3177f419f6ff.png)

**Comment by austinwbest** [comment]
Pushed a change to set explicit sizes on the posters & fixed the table header while i was in there. it now default sorts a-z on the title and removes the sort option from the image/button columns
