### ISSUE TITLE
[Feature Request] Mylar3 Integration

### ISSUE THREAD

**Issue by DrSeussFreak** [Notifiarr/website#20]
[Mylar3](https://github.com/mylar3/mylar3) is for comics, it is based on Headphones so not technically an arr app, but still an amazing app with notifications that could benefit from notifiarr integration.

**Comment by austinwbest** [comment]
Mentioned on discord but just so there is a response for others as well, add https://notifiarr.com/notifierTest.php?testing=Mylar3 as a webhook wherever you can and that will send test payloads for review.

**Comment by austinwbest** [comment]
Its been a year and i dont have any payloads or webhook info. There has also not been any other requests for it so until there is something to move forward with i'll just close this.
