### ISSUE TITLE
[Feature Request] Emby Integration

### ISSUE THREAD

**Issue by BaukeZwart** [Notifiarr/website#23]
I would love to see Emby integration.

**Comment by austinwbest** [comment]
Possible events (Based on screenshot from emby)

- [x] Server update available
- [x] Server restart required
- [x] Plugin installed
- [x] Plugin uninstalled
- [x] Playback start
- [x] Playback pause
- [x] Playback resume (unpause)
- [x] Playback stop
- [x] Playback scrobble
- [ ] Mark favorite
- [x] Mark watched
- [x] Mark unwatched

Others not documented (Payloads where sent though)
- [x] Item rated

Once i have payloads for all these events, it can be added. If you use Emby and want to help send payloads, add a webhook that points to `https://notifiarr.com/notifierTest.php?testing=emby`

**Comment by austinwbest** [comment]
So it seems everything is there except marking something as a favorite. I'm not sure what other "item" based triggers there are but the rated one is the only one received so far.

I'll get started with these triggers, 12 triggers is a fair starting point

**Comment by BaukeZwart** [comment]
I just marked an episode as favorite (had done this before) if it still isn't coming in there probably is something not right at the Emby side.
Also, we asked Emby to add item added, but knowing the Emby devs that can take some time.
Thanks for adding this.
