### ISSUE TITLE
Client Update Notification / Client Out of Date Notification

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#239]
- Notify users that a client update is available to their client channel if configured (toggable)
- Notify users when their client has been out of date for more than X days (14 would match the \*arrs) (no toggle - forced; old client versions are generally unsupported due to breaking changes and development)
   - Client Channel if Configured
   - Error Channel if no client channel?
- If multiple clients are out of date - possibly consolidate to a singular notification

 - Possibly add banner to website notifying them their client(s) are out of date)

**Comment by austinwbest** [comment]
![image](https://user-images.githubusercontent.com/8321115/222292453-08b60521-7a99-48a4-8b6b-02817899149c.png)


Start with this before being intrusive with notifications
