### ISSUE TITLE
More options for emby integration

### ISSUE THREAD

**Issue by PancakeZik** [Notifiarr/website#261]
Helloz

I'm new to notifiarr and I noticed that the emby integration options are much more limited than the others.
Could you please add the option to consolidate the play and stop in one notification like radarr grab and import, and also the option to limit the content of the notifications? Finally, maybe adding the option for content lines for the stopped and paused as well?

Thanks!

**Comment by austinwbest** [comment]
The content for notifications can be added as settings but none of the media apps update existing. Unless you have a very slow server the play would be scrolled out of view and never even see the finish or resume, etc

**Comment by austinwbest** [comment]
Completed on dev, will be in next live push. 150+ settings
