### ISSUE TITLE
[Feature Request] Ability to mask user IP in Plex integration

### ISSUE THREAD

**Issue by sea3pea0** [Notifiarr/website#264]
The geolocation map that shows up in Plex playing notifications is really cool. But if you un-select IP in notifications, the map doesn't show in notifications either. It would be awesome to either be able to mask user IP addresses or have the map still show up when user IP is un-selected

**Comment by austinwbest** [comment]
![image](https://user-images.githubusercontent.com/8321115/218861466-9fe3b571-2fd3-4121-aef5-bed03c7a9ca3.png)

They are not tied together for display so if you turn off the user ip and leave on ip map and that doesn't work then that is a bug.

Adding a mask ip setting is fine too

**Comment by sea3pea0** [comment]
Yeah must be a bug with the map, because if I un-select the "User IP", the map doesn't display.

**Comment by sea3pea0** [comment]
@austinwbest Should I do anything in regards to the bug that doesn't allow the "User IP Map" show when "User IP isn't also selected? Like should I open a separate issue for that? Thanks!

**Comment by austinwbest** [comment]
> @austinwbest Should I do anything in regards to the bug that doesn't allow the "User IP Map" show when "User IP isn't also selected? Like should I open a separate issue for that? Thanks!

![image](https://user-images.githubusercontent.com/8321115/221252330-1042dd43-08a0-42a2-8310-c49c6a19cffd.png)

It is on dev now & will work to live asap
