### ISSUE TITLE
Feature Request - Add link to local Overseerr instance in notification

### ISSUE THREAD

**Issue by hansenc0705** [Notifiarr/website#267]
Much like you can have clickable links for Sonarr/Radarr in the notification it would be nice to have that for Overseerr as well.

**Comment by austinwbest** [comment]
I dont use Overseerr so i have no idea what those links look like for movies, series, episodes, etc. Would need examples

**Comment by hansenc0705** [comment]
Uses TMDB ID for Movies and TV Shows

Examples
TV - https://overseerr_base_url/tv/100088
Movies - https://overseerr_base_url/movie/315162

**Comment by austinwbest** [comment]
Are you on the notifiarr discord server?

**Comment by austinwbest** [comment]
This is added now.
