### ISSUE TITLE
Starr - New Notification Types

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#275]
# Starr

- [X] Sonarr - On Series Add
- [x] Sonarr - On Health Restored https://github.com/Sonarr/Sonarr/pull/5613/files 
- [ ] Sonarr - On Manual Intervention https://github.com/Sonarr/Sonarr/commit/5ec282750bdea16f770282b80fdaec56a65749e2
- [x] Radarr - On Health Restored https://github.com/Radarr/Radarr/commit/8563ed0a203c5974e94e2d8868880ab7e12d430e
- [ ] Radarr - On Manual Intervention https://github.com/Radarr/Radarr/commit/a1e622a3630c477f58aa2b775d189b32766594dc

# Reference

## Sonarr Payloads

  - ref https://github.com/Sonarr/Sonarr/blob/5ec282750bdea16f770282b80fdaec56a65749e2/src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs

## Radarr Payloads

- ref https://github.com/Radarr/Radarr/blob/a1e622a3630c477f58aa2b775d189b32766594dc/src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs#L147

**Comment by austinwbest** [comment]
Considering the `On Manual Intervention` is very limited in its scope to the point it doesnt even do what it says, i am not going to worry about this trigger until someone manages to actually get a payload for it.

Stick with using the built in stuck notifications in the mean time, they cover way more than this does and have way more configuration.
