### ISSUE TITLE
Add ability to action Overseerr notifications

### ISSUE THREAD

**Issue by olig89** [Notifiarr/website#289]
Dream outcome for my use case; As an Overseer admin, I receive a discord notification for a new pending request on my server instance, and within the discord message I have the option to Approve/Reject the request.

My preferred approach would be a set of buttons or even reaction emoji.

Notifiarr already stores the Overseerr URL in the integration Extra Settings, and I believe it could be achieved by updating the request status here: [OverseerrAPI Doc](https://api-docs.overseerr.dev/#/request/post_request__requestId___status_)

**Comment by austinwbest** [comment]
I dont say no to features and settings often but integrating with Overseerr is one of those very few times.

Sorry it isn't the outcome you're after bud & if you want to discuss it further you're welcome to hop on discord and we can.

**Comment by olig89** [comment]
No problem! I can kind of infer why from other Overseerr interactions/references :)

**Comment by olig89** [comment]
In case anyone ends up here from a search and is still looking for an acceptable workaround/solution for accept/reject on Android (probably also for iOS but no way to verify):

1. Within Notifiarr, ensure you set the external Overseer URL properly
2. On the device, open Overseer in your favourite browser and "Add to Homescreen"/"Install as app", if you haven't already
3. Go into the App Permission settings for that installed PWA app and set it as the default for opening links to your overseer public address

That way once Notifiarr sends you the discord message, in the Links section you can click "Open Local" which will take you directly to where you accept/reject the request, in essence only adding one tap to the end-to-end experience.
