### ISSUE TITLE
Sonarr v4 Stable Cleanup

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#306]
cleanup v3 endpoints and add v4
- [ ] remove trash sync for RP
- [ ] remove lang profiles endpoint 
- [ ] remove release profiles endpoint
- [ ] add custom format endpoint
- [ ] other?

![image](https://github.com/Notifiarr/website/assets/55419169/0edba814-1f22-470d-84a3-3165cb934a40)

related client - https://github.com/Notifiarr/notifiarr/issues/648

**Comment by austinwbest** [comment]
As mentioned on the other issue, some things are going to stay as there could be changes in the future that utilize the release profile endpoints. The sync related shit has been removed but the endpoints will hang around for now.

Can add the custom format endpoint to sonarr
Can remove the language profiles endpoint from sonarr

**Comment by austinwbest** [comment]
Done on nightly
