### ISSUE TITLE
[FR] Add ability to Split TRaSH Streaming Services CF into Individual Entries

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#41]
Title

useful for including in rename and noting the specific streaming service

**Comment by austinwbest** [comment]
Im not sure this would work because when trash updates the main CF, it would not be easy to try and figure out what to keep in sync for someone who has split it into multiples. I would think in that case you would just not use his and use your own (multiples) to get what you want?

**Comment by bakerboy448** [comment]
Each specification name would become its own custom format.

https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#streaming-services

matching would be value based for each split custom format

likely would need to split it internally before comparing if someone uses multiples then update as needed

**Comment by austinwbest** [comment]
So if a new one is added, it wouldn't sync it.

If one was deleted, it wouldn't remove it.

Only thing it would do is update the regex for the given split service of it where to be changed. That is what you are expecting?

**Comment by austinwbest** [comment]
This CF no longer exists
