### ISSUE TITLE
Overseerr features

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/website#57]
Add a way to update existing or use a 1:1 for messages (currently 1:1 is only choice)
Add a way to turn on/off message content like the arr apps 

mikenobbs

**Comment by bobokun** [comment]
franticPanic:
Overseerr added in issue reporting over the holidays, and I completely missed the announcement for it. Has anyone else asked about this and having the triggers added in to notifiarr? I searched in the server but didn't see a mention
https://discord.com/channels/764440599066574859/764441447445037086/931770629290623016

**Comment by bobokun** [comment]
Add a way to @mention discord users when their request is available, request is waiting to be approved, etc..

Will need to pass the additional variables:
Notify User:
`{{notifyuser_settings_discordId}}` - The target notification recipient's Discord ID (if set)
Requested:
`{{requestedBy_settings_discordId}}` - The requesting user's Discord ID (if set)
Issue:
`{{reportedBy_settings_discordId}}` - The requesting user's Discord ID (if set)
Comment:
`{{commentedBy_settings_discordId}}` - The commenting user's Discord ID (if set)

![image](https://user-images.githubusercontent.com/12660469/149669568-282ad8d5-696a-4df8-bcd6-892b1bd38741.png)

**Comment by austinwbest** [comment]
Ok, so there are over 100 checkboxes worth of things to turn on and off now & pinging users is also an option but only for requests. If someone leaves a comment, there is no sense to ping them that they left a comment. The notifyuser one, i have no idea which trigger sends it or where it is in the payload so that one was also ignored. 

If someone wants to drop by discord and tell me when that one is used i can add support for it easily enough.
