### ISSUE TITLE
Sonarr Season Pack Notifications

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#59]
Currently for season packs a notification for each episode occurs; for those who have the 1:1 / delete messages configured this means that all episodes generate a notification but ultimately only the final episode's notification is left behind.

Possible solutions:
- detect season pack notifications and hold back related notifications until they stop?
- ????

**Comment by davidnewhall** [comment]
It's all one download anyway, and you chose to combine messages. Doesn't feel like there's much to fix here, but nitsua can explain how this request is impossible. haha

**Comment by bakerboy448** [comment]
It's 1 release and 1 download with many episodes and many notifications.

Pretty sure even with setting 1:1 and not the update that i have it'd still trigger A notification for each and every episode on import

**Comment by austinwbest** [comment]
With 1:1 on, 1 season pack with 10 episodes will be 11 notifications. If delete grab is enabled then it should be 10 notifications since the grab would be deleted.

With 1:1 off, it should be 1 grab which then updates to all the imports leaving 1 notification. If delete grab is enabled then it should delete the grab when the first import comes in and then update that message for the remainder.

With that said, explain what it is doing wrong for which scenario

**Comment by bakerboy448** [comment]
![CBB0E617-EAA0-4EBD-9DB8-11B924326DDA](https://user-images.githubusercontent.com/55419169/140631281-debe02ab-5ba8-4c09-8438-0f911ce27443.png)

settings ^

What's occurring is 1 perpetual notification is happening and ultimately only the final episode is left.

the notification is edited and deleted/created for each import depending on if it is an upgrade or new file. 

For Animaniacs S2 - every episode had a notification at least for a few seconds but only the finally imported episode notification remained.

> updates to all the imports leaving 1 notification

So it's expected to only leave the final episode notification behind and all other notifications would never be seen unless the user is actively looking at discord for the seconds that effectively no notification exists except for the final episode?

Just trying to understand what is currently expected but if it's performing as expected I'd say it's a bit suboptimal.

44 episodes means 44 notifications but only 1 final notification that is viewable and only for the final episode.

**Comment by austinwbest** [comment]
With your current settings, you should see every notification. if 1:1 is off then the same message updates 44 times and you see the final episode that was imported (negating message spam)

**Comment by bakerboy448** [comment]
Welp something is busted then

this is the only notification left from a season pack import 
1311 CDT
![DEC82276-2DF0-46DC-9F88-A112990DB6B1](https://user-images.githubusercontent.com/55419169/140631393-ab0f6ec2-c4b3-4b34-909d-864cf1e36052.png)

**Comment by austinwbest** [comment]
Let me know if this is still an issue after the API conversion and changes i made with that @bakerboy448
