### ISSUE TITLE
Google storage reads incorrectly

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/website#73]
https://discord.com/channels/764440599066574859/764440599621009410/921843762928439316

**Comment by davidnewhall** [comment]
Added a `used` value to all drive space reports in snapshot. At least 1 user is running this version. There may not be a good way to identify a drive, except to add up the _used_ and _free_ space, and check if it's anywhere near the drive _size_. Maybe just sum the _used_ counts to present that value in the UI. We can discuss more.
