### ISSUE TITLE
[Bug] Stupid Sonarr Profiles Yet Again

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#78]
for efforts [post server swap]

and sonarr release profiles are janked again; mine are once again not matching lol
for just 2
save does nothing or does not close the modal
Image
looks like the only thing that would have changed is the damn optionals again
just dumped my profiles from sonarr https://gist.github.com/bakerboy448/22907b0ea8fccb9121ba1987eba14ba7
they appear to be materially similar
P2P Groups + Repack/Proper - has optionals
and 
Anime - Second release profile - has no optionals
do not match

**Comment by bakerboy448** [comment]
Reset profiles pushed from Notifiarr today; will know if they break going forward, they were correct today.

Nit suggested perhaps he just split out the optionals, save headaches for debugging and cut down on the code/effort to check the jsons

**Comment by austinwbest** [comment]
#99
