### ISSUE TITLE
[FR] Kill sessions global settings & configurable triggers (e.g. transcode 4k)

### ISSUE THREAD

**Issue by bobokun** [Notifiarr/website#80]
Set kill sessions on a global level instead of setting the settings per user.

Use case:
>If any users idle for more than 20minutes I want the session to be killed, or if any user has more than 2 devices streaming at a time I want the sessions to be killed (account sharing for example)

https://discord.com/channels/764440599066574859/764440599621009410/925766838409912330

**Comment by bakerboy448** [comment]
Add `killstreams` functionality to kill by quality (transcode)
w/ config message "Transcoding streams are not allowed for {video_resolution} (4K) streams. Choose a different version of the video and_or change Plexs Remote Streaming Quality Settings."

Ref https://github.com/blacktwin/JBOPS/tree/master/killstream

![image](https://user-images.githubusercontent.com/55419169/151565743-80311391-2533-4af3-85f8-d9c10e716159.png)

![image](https://user-images.githubusercontent.com/55419169/151565617-eda749e1-d689-4f55-a93e-bfc26ca1e2ca.png)

**Comment by austinwbest** [comment]
Available on dev
