### ISSUE TITLE
multiple channel specification for dashboard module 

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/website#82]
kaizen

**Comment by bullmoose20** [comment]
Will this feature allow for us to be able to specify different discord error channels per notifiarr “card” within Notifiarr.com?

**Comment by austinwbest** [comment]
> Will this feature allow for us to be able to specify different discord error channels per notifiarr “card” within Notifiarr.com?

No, different request but that one is already done :)

**Comment by austinwbest** [comment]
Ok, each dashboard item can be split into different channels via the channel picker
