### ISSUE TITLE
Split error channel

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/website#96]
Now that there is alot more integrations, remove the global error channel and let each integration that uses it have its own channel

**Comment by bullmoose20** [comment]
Would love to see this one happen…with all these great notifications, “triaging” the barrage of error messages to their own channels based on the notifiarr card integration sending the error to discord, would be great.

**Comment by quorn23** [comment]
As the health alerts probably never were planned to get triaged, in such an extensive way as Notifiarr has become, it would be nice if we can get some slightly more fine tuning with it.
Example - Indexer or Tracker is unavailable, currently that triggers a health alert for every *arr running, which has added the indexer/tracker. Meaning one "error" results in a message from Prowlarr,Radarr,Sonarr,Lidarr, etc each. 

Those specific messages come from the "Area Indexers", so it would be desirable to suppress them for all arrs besides Prowlarr for example. 

Austin, as you're involved in the arr development, maybe having the option to turn each available "Area" on or off would be a possibility? I assume you have more insight in this, than us users.

**Comment by nemchik** [comment]
I would love if every notification type would have ping options (user/role like `Error channel pings`, but for anything).
![Screenshot_20220201-191810](https://user-images.githubusercontent.com/725456/152078326-b0eac19b-01e8-4199-a36b-1c3fe5331944.png)
Basically have both select lists (user/role) next to each notification type. Then I could choose to get notifications for errors from all services but only get pings for the services I consider high priority. Also maybe I'd like pings for upgrades (I don't, but maybe someone does).

**Comment by davidnewhall** [comment]
I love that idea too.

**Comment by austinwbest** [comment]
> I would love if every notification type would have ping options (user/role like `Error channel pings`, but for anything). 

```51 files changed, 773 insertions(+), 312 deletions(-)```
This part is done. Once i split the error channel it'll all be pushed together
