### ISSUE TITLE
[BUG] - CF Loop - Site Not matching CFs correctly and Saying exact matches do not match (update loop)

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/website#98]
![image](https://user-images.githubusercontent.com/55419169/150435853-35017bf5-5342-417b-b2ae-7d0320a06e6d.png)

Site is stuck in a CF loop for two custom formats that match the exact json and fails to match a 3rd.
all 3 are exact matches to the notifiarr json and yet 

- Radarr CF x265 fails to match to x265 on the site
- Radarr CF x265 (720/1080p)  is not matched to x265 (720/1080p) on the site
- Site is incorrectly trying to match Radarr x265 to site x265 (720/1080p)
- Site is repeatedly updating 1080p thinking the exact json is out of sync

![image](https://user-images.githubusercontent.com/55419169/150436161-8f55c142-7849-402b-86b7-bedf3ac6fdd4.png)

x265 from radarr
```json
{
  "name": "x265",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "x265",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "[xh][ .]?265|\bHEVC(\b|\\d)"
      }
    },
    {
      "name": "Remux",
      "implementation": "QualityModifierSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 5
      }
    }
  ]
}
```
x265 (720/1080p)
```json
{
  "name": "x265 (720/1080p)",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "720p",
      "implementation": "ResolutionSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 720
      }
    },
    {
      "name": "1080p",
      "implementation": "ResolutionSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 1080
      }
    },
    {
      "name": "x265/HEVC",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "[xh][ .]?265|\bHEVC(\b|\\d)"
      }
    }
  ]
}
```
likely related - x265 does not match, yet is also matching json
![image](https://user-images.githubusercontent.com/55419169/150436712-e0bbe7ac-cd63-47e1-be9e-57983af83604.png)
```json
{
  "name": "x265",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "x265",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "[xh][ .]?265|\bHEVC(\b|\\d)"
      }
    },
    {
      "name": "Remux",
      "implementation": "QualityModifierSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 5
      }
    }
  ]
}
```
-----
![image](https://user-images.githubusercontent.com/55419169/150436366-54cf7c5d-aafd-457a-91c3-69a3510df332.png)

```json
{
  "name": "1080p - Notifiarr",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "1080p",
      "implementation": "ResolutionSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 1080
      }
    }
  ]
}
```

**Comment by bakerboy448** [comment]
- Custom Format Sync fails if 1 custom format of a group fails to sync https://github.com/Notifiarr/notifiarr/issues/166
- x265 in Radarr was incorrectly being matched to `x265 (720/1080p)` on the site
- CF name sync is enabled
- Site was trying to update x265 in radarr to be named `x265 (720/1080p)` which was not unique and thus due to the aforementioned client issue the syncs were looping

**Comment by austinwbest** [comment]
This is fixed on the site side. The failing part of the client is not related to the matching but is also being sorted with a test build
